vrpn_client_node:
  ros__parameters:
    server: 192.168.1.111
    port: 3883
    frame_id: "world"
    use_server_time: false
    refresh_tracker_frequency: 1.0
    update_frequency: 100.0
    broadcast_tf: true
